### ISSUE TITLE
SANE backend segfaults when trying to adjust unsupported options

### ISSUE THREAD

**Issue by J5lx** [stefantalpalaru/GTS#2]
Every time I hit the Preview entry in the Scanning menu while my webcam is selected as scanner (since I'm too lazy to connect my actual scanner just for having a quick look at the program), GTS segfaults. When I select the test backend, however, it works just fine. From a quick glance at the code it seems that GTS automatically sets the resolution when previewing, but since my webcam apparently doesn't support the resolution option(s), the respective descriptor in `_option_info` is still `NULL`. When `adjust_option_value()` then tries to `switch(option->desc->constraint_type)` it fails since `option->desc` points nowhere.

*Edit:* I guess the function should just return then, but I haven't had a closer look at the GTS code so I'm not quite sure.

**Comment by stefantalpalaru** [comment]
Segfault fixed, but the webcam support will need more work.

**Comment by J5lx** [comment]
I see. Just so you know: Webcam support isn't a priority for me; it's just something I used because I was lazy (as explained in the OP). The segfault was the only thing I was really worried about.
